version: "2.0"
services:
  gv_app:
    container_name: gv_app
    build: .
    ports:
      - "3001"
    links:
      - gv_postgres:db
      - gv_mailserver:mail
    environment:
      EMAIL_PW: "${EMAIL_PW}"
      GV_PG_PASS: "${GV_PG_PASS}"
      SUNLIGHT_API_KEY: "${SUNLIGHT_API_KEY}"
  gv_proxy:
    container_name: gv_proxy
    image: nginx:latest
    links:
      - gv_app:app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www:ro
    ports:
      - "8080:8080"
  gv_postgres:
    container_name: gv_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${GV_PG_PASS}"
      POSTGRES_USER: docker
  gv_mailserver:
    container_name: gv_mailserver
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: stopgunviolence.today
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/

