version: "2.0"
services:
  gv_app:
    container_name: gv_app
    build: .
    ports:
      - "3001"
    links:
      - gv_postgres:db
    environment:
      EMAIL_PW: "${EMAIL_PW}"
      GV_PG_PASS: "${GV_PG_PASS}"
      SUNLIGHT_API_KEY: "${SUNLIGHT_API_KEY}"
  gv_proxy:
    container_name: gv_proxy
    image: nginx:latest
    links:
      - gv_app:app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www:ro
    ports:
      - "8080:8080"
  gv_postgres:
    container_name: gv_postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${GV_PG_PASS}"
      POSTGRES_USER: docker

